name = "hardcover"
license = "MIT"
licenselink = "https://github.com/"
description = "Minimalist theme for Hugo."
homepage = "https://github.com/alexander-e/hardcover"
tags = ["minimalist", "reading", "sepia", "academic"]
features = ["blog"]
min_version = 0.15

[author]
name = "Alexander Erreygers"
homepage = "http://users.ugent.be/~aerreyge"
